// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWOdY0pBzynMdJ3eu53QjHxOpya4Zl-5M',
    appId: '1:111551813367:web:48730725142dbb990d65f2',
    messagingSenderId: '111551813367',
    projectId: 'homefirebase-9bc0d',
    authDomain: 'homefirebase-9bc0d.firebaseapp.com',
    storageBucket: 'homefirebase-9bc0d.appspot.com',
    measurementId: 'G-2XK91JQ23J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCcuyLtGo8mvfUVRXMfMJ_rhRmh-ULo-4',
    appId: '1:111551813367:android:7edd5c8845992d850d65f2',
    messagingSenderId: '111551813367',
    projectId: 'homefirebase-9bc0d',
    storageBucket: 'homefirebase-9bc0d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBAjs1NXC6IHKazufUCasMkWUC3Pgsebg',
    appId: '1:111551813367:ios:fa375b933ab6446f0d65f2',
    messagingSenderId: '111551813367',
    projectId: 'homefirebase-9bc0d',
    storageBucket: 'homefirebase-9bc0d.appspot.com',
    iosBundleId: 'com.example.demofirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBAjs1NXC6IHKazufUCasMkWUC3Pgsebg',
    appId: '1:111551813367:ios:fa375b933ab6446f0d65f2',
    messagingSenderId: '111551813367',
    projectId: 'homefirebase-9bc0d',
    storageBucket: 'homefirebase-9bc0d.appspot.com',
    iosBundleId: 'com.example.demofirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWOdY0pBzynMdJ3eu53QjHxOpya4Zl-5M',
    appId: '1:111551813367:web:4b7f38e2d063941c0d65f2',
    messagingSenderId: '111551813367',
    projectId: 'homefirebase-9bc0d',
    authDomain: 'homefirebase-9bc0d.firebaseapp.com',
    storageBucket: 'homefirebase-9bc0d.appspot.com',
    measurementId: 'G-45WWGTR68B',
  );
}
