// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeLUyqHxkIjQ0eA6WAvlTGMYr-W-ncA94',
    appId: '1:639055702718:web:87f5ae3532b9f082e1ccef',
    messagingSenderId: '639055702718',
    projectId: 'fir-registration-e6e2b',
    authDomain: 'fir-registration-e6e2b.firebaseapp.com',
    storageBucket: 'fir-registration-e6e2b.appspot.com',
    measurementId: 'G-X18BMXZ4TM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1W17F3s7C0PjYkH-Vx3emQTwt0mMK8FM',
    appId: '1:639055702718:android:410372da297a1277e1ccef',
    messagingSenderId: '639055702718',
    projectId: 'fir-registration-e6e2b',
    storageBucket: 'fir-registration-e6e2b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7R5HXJSlP8ZT68AgqePyjoCxBtrgrNM8',
    appId: '1:639055702718:ios:be75bc1ffd7eec1ce1ccef',
    messagingSenderId: '639055702718',
    projectId: 'fir-registration-e6e2b',
    storageBucket: 'fir-registration-e6e2b.appspot.com',
    iosBundleId: 'com.example.registrationWithFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7R5HXJSlP8ZT68AgqePyjoCxBtrgrNM8',
    appId: '1:639055702718:ios:be75bc1ffd7eec1ce1ccef',
    messagingSenderId: '639055702718',
    projectId: 'fir-registration-e6e2b',
    storageBucket: 'fir-registration-e6e2b.appspot.com',
    iosBundleId: 'com.example.registrationWithFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDeLUyqHxkIjQ0eA6WAvlTGMYr-W-ncA94',
    appId: '1:639055702718:web:f8f0eff0cfeb4c72e1ccef',
    messagingSenderId: '639055702718',
    projectId: 'fir-registration-e6e2b',
    authDomain: 'fir-registration-e6e2b.firebaseapp.com',
    storageBucket: 'fir-registration-e6e2b.appspot.com',
    measurementId: 'G-NB23XZ9HR1',
  );
}
